Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 20
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      DBName: myfirstdb
      Engine: MySQL #DB Engine 
      MasterUsername: pradeepravi
      MasterUserPassword: prady78953
  
